# Poetry pyproject.toml: https://python-poetry.org/docs/pyproject/
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "parea-ai"
packages = [{ include = "parea" }]
version = "0.2.219"
description = "Parea python sdk"
readme = "README.md"
authors = ["joel-parea-ai <joel@parea.ai>"]
license = "Apache Software License 2.0"
repository = "https://github.com/parea-ai/parea-sdk"
homepage = "https://github.com/parea-ai/parea-sdk"

# Keywords description https://python-poetry.org/docs/pyproject/#keywords
keywords = []

# Pypi classifiers: https://pypi.org/classifiers/
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]


[tool.poetry.dependencies]
python = ">=3.9,<4.0"
httpx = ">=0.28.1"
python-dotenv = "^1.0.1"
poetry-plugin-dotenv = "^2.6.1"
pyupgrade = "^3.19.1"
contextvars = "^2.4"
openai = "*"
pysbd = "^0.3.4"
cattrs = ">=22.1.0"
tiktoken = ">=0.5.2"
levenshtein = "^0.26.1"
pytz = "^2024.2"
wrapt = "^1.17.2"
tenacity = "*"
orjson = "^3.10.14"

[tool.poetry.group.dev.dependencies]
instructor = "^1.7.2"
bandit = "^1.7.1"
black = { version = "^24.1.0", allow-prereleases = true }
darglint = "^1.8.1"
isort = { extras = ["colors"], version = "^5.10.1" }
mypy = "^1.4.1"
mypy-extensions = "^1.0.0"
pre-commit = "^3.3.3"
pydocstyle = "^6.1.1"
pylint = "^3.0.3"
pytest = "^8.0.0"
pyupgrade = "^3.9.0"
coverage = "^7.2.7"
coverage-badge = "^1.1.0"
pytest-html = "^4.1.1"
pytest-cov = "^4.1.0"
langchain = "*"
langchainhub = "*"
faiss-cpu = "^1.7.4"
langchain-experimental = "*"
langchain-community = "*"
langchain-core = "*"
anthropic = "^0.25.1"
ragas = "*"
html2text = "^2020.1.16"
boto3 = "^1.34.6"
langchain-openai = "*"
pinecone-client = "^3.1.0"
guidance = "^0.1.13"
markdownify = "^0.12.1"
routellm = { extras = ["eval", "serve"], version = "^0.2.0" }
cohere = "^5.6.2"


[tool.poetry.scripts]
parea = 'parea:main'


[tool.black]
# https://github.com/psf/black
target-version = ["py39"]
line-length = 180
color = true

exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | env
    | venv
)/
'''

[tool.isort]
# https://github.com/timothycrosley/isort/
py_version = 39
line_length = 180

known_typing = ["typing", "types", "typing_extensions", "mypy", "mypy_extensions"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
include_trailing_comma = true
profile = "black"
multi_line_output = 3
indent = 4
color_output = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html#using-a-pyproject-toml-file
python_version = 3.9
pretty = true
show_traceback = true
color_output = true

allow_redefinition = false
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
ignore_missing_imports = true
implicit_reexport = false
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
strict_optional = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true


[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs = ["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]
doctest_optionflags = ["NUMBER", "NORMALIZE_WHITESPACE", "IGNORE_EXCEPTION_DETAIL"]

# Extra options:
addopts = [
  "--strict-markers",
  "--tb=short",
  "--doctest-modules",
  "--doctest-continue-on-failure",
]

[tool.coverage.run]
source = ["tests"]

[coverage.paths]
source = "parea"

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true
